FROM python:3.11-slim
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /app

# 1. Copy the project file (now it's in the current directory)
COPY pyproject.toml .

# 2. Install dependencies
RUN uv pip install --system --no-cache .

# 3. Copy the app folder
COPY app/ /app/app/

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]